const mongoose = require('mongoose');

const searchHistorySchema = new mongoose.Schema({
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    sessionId: { type: String, index: true },
    query: { type: String, required: true, trim: true },
    normalizedQuery: { type: String, trim: true },
    resultsCount: { type: Number, default: 0 },
    filters: {
        category: String,
        gender: String,
        minPrice: Number,
        maxPrice: Number,
        brand: String,
        color: String,
        size: String,
        sortBy: String
    },
    clickedProductIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Product' }],
    addedToCart: { type: Boolean, default: false },
    convertedToOrder: { type: Boolean, default: false },
    orderId: { type: mongoose.Schema.Types.ObjectId, ref: 'Order' },
    responseTime: { type: Number, default: 0 }, // ms
    deviceType: { type: String, enum: ['desktop', 'mobile', 'tablet'], default: 'desktop' },
    ipAddress: String,
    userAgent: String
}, { timestamps: true });

searchHistorySchema.index({ userId: 1, createdAt: -1 });
searchHistorySchema.index({ sessionId: 1, createdAt: -1 });
searchHistorySchema.index({ query: 'text' });
searchHistorySchema.index({ createdAt: -1 });

const trendingSearchSchema = new mongoose.Schema({
    query: { type: String, required: true, unique: true, trim: true },
    normalizedQuery: { type: String, trim: true },
    count: { type: Number, default: 1 },
    avgResultsCount: { type: Number, default: 0 },
    clickThroughRate: { type: Number, default: 0 },
    conversionRate: { type: Number, default: 0 },
    lastSearchedAt: { type: Date, default: Date.now },
    relatedQueries: [String],
    category: String,
    isActive: { type: Boolean, default: true },
    rank: { type: Number, default: 0 },
    growthRate: { type: Number, default: 0 }, // percentage growth
    seasonality: { type: String, enum: ['year-round', 'seasonal', 'event-based'], default: 'year-round' }
}, { timestamps: true });

trendingSearchSchema.index({ count: -1, updatedAt: -1 });
trendingSearchSchema.index({ query: 'text' });
trendingSearchSchema.index({ rank: 1 });

const searchSynonymSchema = new mongoose.Schema({
    term: { type: String, required: true, trim: true, lowercase: true },
    synonyms: [{ type: String, trim: true, lowercase: true }],
    isActive: { type: Boolean, default: true },
    autoGenerated: { type: Boolean, default: false },
    confidence: { type: Number, default: 1, min: 0, max: 1 },
    usageCount: { type: Number, default: 0 },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });

searchSynonymSchema.index({ term: 1 }, { unique: true });
searchSynonymSchema.index({ synonyms: 1 });

const searchAnalyticsSchema = new mongoose.Schema({
    date: { type: Date, required: true },
    totalSearches: { type: Number, default: 0 },
    uniqueQueries: { type: Number, default: 0 },
    zeroResultsQueries: { type: Number, default: 0 },
    zeroResultsRate: { type: Number, default: 0 },
    avgResultsPerSearch: { type: Number, default: 0 },
    avgResponseTime: { type: Number, default: 0 },
    topQueries: [{
        query: String,
        count: Number,
        avgResults: Number,
        ctr: Number,
        conversionRate: Number
    }],
    searchesByDevice: {
        desktop: { type: Number, default: 0 },
        mobile: { type: Number, default: 0 },
        tablet: { type: Number, default: 0 }
    },
    searchesByCategory: [{
        category: String,
        count: Number,
        avgResults: Number
    }],
    conversionRate: { type: Number, default: 0 },
    revenueAttributed: { type: Number, default: 0 },
    abandonedSearches: { type: Number, default: 0 },
    refinementsCount: { type: Number, default: 0 }
}, { timestamps: true });

searchAnalyticsSchema.index({ date: -1 }, { unique: true });

const searchSuggestionSchema = new mongoose.Schema({
    query: { type: String, required: true, trim: true },
    type: { type: String, enum: ['product', 'category', 'brand', 'query', 'trending'], default: 'query' },
    productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
    category: { type: String, trim: true },
    brand: { type: String, trim: true },
    image: String,
    score: { type: Number, default: 0 },
    isActive: { type: Boolean, default: true },
    clickCount: { type: Number, default: 0 },
    conversionCount: { type: Number, default: 0 }
}, { timestamps: true });

searchSuggestionSchema.index({ query: 1, type: 1 });
searchSuggestionSchema.index({ type: 1, score: -1 });

const productRecommendationSchema = new mongoose.Schema({
    productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
    recommendedProductIds: [{
        productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
        score: { type: Number, required: true, min: 0, max: 1 },
        reason: { type: String, enum: ['collaborative', 'content-based', 'hybrid', 'popularity', 'similarity', 'co-purchase', 'view-also-viewed', 'bought-also-bought', 'category-affinity', 'brand-affinity'], default: 'hybrid' },
        weight: { type: Number, default: 1 }
    }],
    algorithm: { type: String, enum: ['collaborative-filtering', 'content-based', 'hybrid', 'matrix-factorization', 'neural-network'], default: 'hybrid' },
    version: { type: Number, default: 1 },
    isActive: { type: Boolean, default: true },
    lastTrainedAt: Date,
    trainingDataSize: { type: Number, default: 0 },
    metrics: {
        precision: { type: Number, default: 0 },
        recall: { type: Number, default: 0 },
        f1Score: { type: Number, default: 0 },
        coverage: { type: Number, default: 0 },
        diversity: { type: Number, default: 0 },
        novelty: { type: Number, default: 0 }
    }
}, { timestamps: true });

productRecommendationSchema.index({ productId: 1 }, { unique: true });
productRecommendationSchema.index({ isActive: 1 });

const comparisonListSchema = new mongoose.Schema({
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    sessionId: { type: String, index: true },
    name: { type: String, trim: true, maxlength: 100 },
    productIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Product' }],
    maxProducts: { type: Number, default: 4 },
    isPublic: { type: Boolean, default: false },
    shareToken: { type: String, unique: true, sparse: true },
    viewCount: { type: Number, default: 0 },
    convertedToCart: { type: Boolean, default: false },
    convertedToOrder: { type: Boolean, default: false }
}, { timestamps: true });

comparisonListSchema.index({ userId: 1, createdAt: -1 });
comparisonListSchema.index({ sessionId: 1 });

const recentlyViewedProductSchema = new mongoose.Schema({
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    sessionId: { type: String, index: true },
    productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
    viewedAt: { type: Date, default: Date.now },
    viewDuration: { type: Number, default: 0 }, // seconds
    referrer: String,
    source: { type: String, enum: ['homepage', 'category', 'search', 'product-page', 'cart', 'wishlist', 'email', 'recommendation', 'social', 'direct'], default: 'direct' },
    deviceType: { type: String, enum: ['desktop', 'mobile', 'tablet'], default: 'desktop' }
}, { timestamps: true });

recentlyViewedProductSchema.index({ userId: 1, viewedAt: -1 });
recentlyViewedProductSchema.index({ sessionId: 1, viewedAt: -1 });
recentlyViewedProductSchema.index({ productId: 1, viewedAt: -1 });

const productAffinitySchema = new mongoose.Schema({
    productId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
    relatedProductId: { type: mongoose.Schema.Types.ObjectId, ref: 'Product', required: true },
    affinityType: { 
        type: String, 
        enum: ['co-purchase', 'co-view', 'co-cart', 'category-sibling', 'brand-sibling', 'similar-attributes', 'complementary', 'substitute', 'upgrade', 'accessory'],
        required: true 
    },
    strength: { type: Number, required: true, min: 0, max: 1 },
    coOccurrenceCount: { type: Number, default: 0 },
    orderCount: { type: Number, default: 0 },
    viewCount: { type: Number, default: 0 },
    cartCount: { type: Number, default: 0 },
    lastCalculatedAt: { type: Date, default: Date.now },
    isActive: { type: Boolean, default: true }
}, { timestamps: true });

productAffinitySchema.index({ productId: 1, relatedProductId: 1 }, { unique: true });
productAffinitySchema.index({ productId: 1, strength: -1 });
productAffinitySchema.index({ affinityType: 1, strength: -1 });

module.exports = {
    SearchHistory: mongoose.model('SearchHistory', searchHistorySchema),
    TrendingSearch: mongoose.model('TrendingSearch', trendingSearchSchema),
    SearchSynonym: mongoose.model('SearchSynonym', searchSynonymSchema),
    SearchAnalytics: mongoose.model('SearchAnalytics', searchAnalyticsSchema),
    SearchSuggestion: mongoose.model('SearchSuggestion', searchSuggestionSchema),
    ProductRecommendation: mongoose.model('ProductRecommendation', productRecommendationSchema),
    ComparisonList: mongoose.model('ComparisonList', comparisonListSchema),
    RecentlyViewedProduct: mongoose.model('RecentlyViewedProduct', recentlyViewedProductSchema),
    ProductAffinity: mongoose.model('ProductAffinity', productAffinitySchema)
};